import test from 'node:test';
import assert from 'node:assert/strict';
import {validateInput,validateOutput} from '../netlify/functions/lib/contract.mjs';
import {CATEGORIES,BARRETT,BLOOM,LABELS} from '../netlify/functions/lib/rubrics.mjs';
import {handleRequest as handler} from '../netlify/functions/analyze.mjs';
const input={blueprint:{type:'Pilihan Ganda',genre:'Narrative',barrett:BARRETT[2],kisi:'Infer character traits based on actions in the narrative',bloom:BLOOM[1],cefr:'A2'},grade:7,stimuli:['Rina helped an old woman.'],question:'What is Rina like? A. Kind B. Lazy C. Rude D. Selfish'};
const output=()=>({answerKey:{status:'Ditentukan',answer:'A. Kind',explanation:'She helped the woman.'},categories:CATEGORIES.map(([id],i)=>({id,score:80+i,label:LABELS[1],target:'Target',identified:'Identified',analysis:'Analisis',evidence:'Bukti'})),overall:{label:LABELS[1],reason:'Simpulan'},grammar:{summary:'Tidak ada kesalahan.',notes:[]},issues:[],revision:{stimuli:[...input.stimuli],question:input.question,rationale:'Perbaikan kecil.',answerKey:{status:'Ditentukan',answer:'A. Kind',explanation:'Evidence.'}}});
test('input supports a free question type and one or two texts',()=>{assert.equal(validateInput(input).grade,7);assert.equal(validateInput({...input,blueprint:{...input.blueprint,type:'Kategori khusus'},stimuli:['Text A','Text B']}).stimuli.length,2);});
test('reject blank fields, wrong enums, extra texts, grade and oversize',()=>{for(const candidate of [{...input,question:'  '},{...input,grade:13},{...input,stimuli:['a','b','c']},{...input,stimuli:['']},{...input,blueprint:{...input.blueprint,bloom:'C9'}},{...input,question:'x'.repeat(12001)}])assert.throws(()=>validateInput(candidate));});
test('calculate mean instead of trusting AI; order categories',()=>{const x=output();x.overall.score=100;x.categories.reverse();const r=validateOutput(x,input);assert.equal(r.overall.score,83);assert.equal(r.categories[0].id,'type');});
test('omit revision whenever overall is Sangat Sesuai',()=>{const x=output();x.overall.label=LABELS[0];assert.equal('revision' in validateOutput(x,input),false);});
test('all other labels require a whole revision with matching text count',()=>{const x=output();delete x.revision;assert.throws(()=>validateOutput(x,input));assert.throws(()=>validateOutput(output(),{...input,stimuli:['a','b']}));const y=output();y.revision.stimuli=['a','b'];assert.equal(validateOutput(y,{...input,stimuli:['a','b']}).revision.stimuli.length,2);});
test('reject duplicate categories, unknown labels and invalid scores',()=>{const a=output();a.categories[0].id='genre';assert.throws(()=>validateOutput(a,input));const b=output();b.categories[0].score=101;assert.throws(()=>validateOutput(b,input));const c=output();c.overall.label='Excellent';assert.throws(()=>validateOutput(c,input));});
test('HTTP method, content type, invalid input and missing key have clear errors',async()=>{assert.equal((await handler({httpMethod:'GET'})).statusCode,405);assert.equal((await handler({httpMethod:'POST',headers:{},body:'{}'})).statusCode,415);assert.equal((await handler({httpMethod:'POST',headers:{'content-type':'application/json'},body:'{}'})).statusCode,400);const old=process.env.GROQ_API_KEY;delete process.env.GROQ_API_KEY;try{assert.equal((await handler({httpMethod:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(input)})).statusCode,503);}finally{if(old)process.env.GROQ_API_KEY=old;}});
test('proxy requests structured JSON, returns validated result, handles quota/truncation',async()=>{const originalFetch=global.fetch,oldKey=process.env.GROQ_API_KEY;process.env.GROQ_API_KEY='test-only-secret';const event={httpMethod:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(input)};try{global.fetch=async(url,opts)=>{assert.equal(opts.headers.Authorization,'Bearer test-only-secret');assert.equal(new URL(url).hostname,'api.groq.com');assert.equal(opts.headers['x-goog-api-key'],undefined);assert.ok(!url.includes('test-only-secret'));const body=JSON.parse(opts.body);assert.equal(body.response_format.type,'json_schema');assert.equal(body.response_format.json_schema.strict,true);assert.ok(body.messages[0].content.includes('C6 Create:'));assert.ok(body.messages[0].content.includes('KATEGORI LAIN:'));return {ok:true,json:async()=>({choices:[{finish_reason:'stop',message:{content:JSON.stringify(output())}}]})};};const response=await handler(event);assert.equal(response.statusCode,200);assert.equal(JSON.parse(response.body).result.overall.score,83);assert.ok(!response.body.includes('test-only-secret'));global.fetch=async()=>({ok:false,status:401});assert.equal((await handler(event)).statusCode,503);global.fetch=async()=>({ok:true,json:async()=>({choices:[{finish_reason:'length'}]})});assert.equal((await handler(event)).statusCode,502);}finally{global.fetch=originalFetch;if(oldKey)process.env.GROQ_API_KEY=oldKey;else delete process.env.GROQ_API_KEY;}});
test('original and revised answer keys required, ambiguous answer permitted',()=>{const x=output();delete x.answerKey;assert.throws(()=>validateOutput(x,input));const y=output();delete y.revision.answerKey;assert.throws(()=>validateOutput(y,input));const z=output();z.answerKey={status:'Ambigu',answer:'A atau B',explanation:'Dua opsi sama-sama didukung teks.'};assert.equal(validateOutput(z,input).answerKey.status,'Ambigu');});
test('analysis completes without revision and separate revision endpoint checks whole output',async()=>{
 const {handleRequest:revise}=await import('../netlify/functions/revise.mjs');
 const originalFetch=global.fetch,oldKey=process.env.GROQ_API_KEY;process.env.GROQ_API_KEY='test-only';
 const analysis=output();delete analysis.revision;
 const event=body=>({httpMethod:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});
 try{
  global.fetch=async(url,opts)=>{const body=JSON.parse(opts.body);assert.equal(body.response_format.json_schema.schema.properties.revision,undefined);return {ok:true,json:async()=>({choices:[{finish_reason:'stop',message:{content:JSON.stringify(analysis)}}]})};};
  const result=await handler(event(input));assert.equal(result.statusCode,200);assert.equal(JSON.parse(result.body).result.revision,undefined);
  global.fetch=async(url,opts)=>{const body=JSON.parse(opts.body);assert.ok(body.messages[0].content.includes('PENYESUAIAN CEFR'));assert.ok(body.response_format.json_schema.schema.required.includes('answerKey'));return {ok:true,json:async()=>({choices:[{finish_reason:'stop',message:{content:JSON.stringify(output().revision)}}]})};};
  const revision=await revise(event({input,analysis}));assert.equal(revision.statusCode,200);assert.equal(JSON.parse(revision.body).revision.question,input.question);
  assert.equal((await revise(event({input,analysis:{}}))).statusCode,400);
 }finally{global.fetch=originalFetch;if(oldKey)process.env.GROQ_API_KEY=oldKey;else delete process.env.GROQ_API_KEY;}
});
