import {writeFile} from 'node:fs/promises';
import {CATEGORIES,CRITERIA,LEVELS,RUBRIC_VERSION,REFERENCES} from '../netlify/functions/lib/rubrics.mjs';
const e=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const html=`<!doctype html><html lang="id"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Rubrik Telaah Butir Soal</title>
<style>body{font:16px/1.7 Arial,sans-serif;color:#272c40;background:#f6f8fd;margin:0}main{max-width:920px;margin:30px auto;padding:28px;background:white;border:1px solid #dce2ef;border-radius:16px}h1,h2{color:#543784;line-height:1.3}h1{font-size:2rem}h2{font-size:1.3rem;margin-top:30px}a{color:#543784}table{border-collapse:collapse;width:100%;font-size:.93rem}th,td{padding:12px;border:1px solid #dce2ef;text-align:left;vertical-align:top}th{background:#edf3ff}li{margin:7px 0}.note{background:#f0eafa;border-radius:10px;padding:18px}@media(max-width:600px){main{margin:0;padding:20px;border:0;border-radius:0}th,td{padding:8px}}@media print{main{margin:0;border:0}a.back{display:none}}</style>
<main><a class="back" href="index.html">← Aplikasi analisis soal</a><h1>Rubrik Telaah Butir Soal</h1><p>Versi ${e(RUBRIC_VERSION)} · Rubrik operasional aplikasi untuk guru Bahasa Inggris.</p>
<p class="note">Rubrik ini menilai kesesuaian soal dengan target yang dimasukkan. Skala angka dan batas label disusun untuk aplikasi, bukan skala resmi Barrett, Bloom, atau CEFR. Hasil tetap perlu dikalibrasi dengan telaah guru; tidak mengukur kesukaran empiris, daya beda, atau reliabilitas tes.</p>
<h2>1. Patokan penilaian</h2><p>Tujuh kategori berbobot sama. Setiap kategori memiliki empat kriteria, masing-masing diberi level 0–4 berdasarkan bukti. Penilaian dimulai dari kunci dan tuntutan minimum untuk menjawab, kemudian dibandingkan dengan target.</p><ul>${LEVELS.map(x=>'<li>'+e(x)+'</li>').join('')}</ul>
<p>Level 0 karena bukti tidak tersedia berarti kesesuaian belum dapat dibuktikan; tidak sama dengan kepastian bahwa soalnya salah. Alasan harus membedakan keduanya. Preferensi gaya atau keinginan membuat soal lebih sulit tidak menjadi alasan menurunkan nilai.</p>
<h2>2. Kriteria tiap kategori</h2><table><thead><tr><th>Kategori</th><th>Empat kriteria, urut 1–4</th></tr></thead><tbody>${CATEGORIES.map(([id,name])=>'<tr><th>'+e(name)+'</th><td><ol>'+CRITERIA[id].map(x=>'<li>'+e(x)+'</li>').join('')+'</ol></td></tr>').join('')}</tbody></table>
<h2>3. Perhitungan dan label</h2><p>Skor kategori = maksimum antara 1 dan pembulatan (jumlah empat level ÷ 16 × 100). Contoh: [4, 4, 3, 3] menghasilkan 88; [3, 3, 3, 3] menghasilkan 75; [0, 0, 0, 0] ditampilkan sebagai 1 untuk mempertahankan skala aplikasi 1–100. Skor keseluruhan adalah rata-rata tujuh skor kategori; label ditentukan dari angka sebelum pembulatan tampilan.</p>
<table><tr><th>Skor dasar</th><th>Label</th></tr><tr><td>90–100</td><td>Sangat Sesuai</td></tr><tr><td>75 sampai kurang dari 90</td><td>Sesuai</td></tr><tr><td>50 sampai kurang dari 75</td><td>Kurang Sesuai</td></tr><tr><td>Di bawah 50</td><td>Tidak Sesuai</td></tr></table>
<p>Label akhir adalah keputusan kelayakan berdasarkan aturan berikut; angka rata-rata tetap ditampilkan apa adanya:</p><ul><li>Sangat Sesuai memerlukan seluruh kategori minimal 75, tanpa isu material dan tanpa kesalahan grammar nyata.</li><li>Jika ada kategori di bawah 50, label maksimal Kurang Sesuai.</li><li>Jika kunci Ambigu atau Informasi tidak cukup, termasuk salah satu baris kategori, label maksimal Kurang Sesuai.</li><li>Label tidak pernah dinaikkan oleh aturan pembatas. Revisi ditampilkan untuk semua label selain Sangat Sesuai.</li></ul>
<h2>4. Aturan klasifikasi</h2><p>Barrett menilai pemahaman bacaan: informasi eksplisit (Literal), pengolahan kembali informasi eksplisit (Reorganization), simpulan tersirat (Inferential), penilaian dengan bukti/kriteria (Evaluation), dan respons estetis/emosional (Appreciation). Jika soal bukan pemahaman bacaan, keterbatasan penerapannya harus dinyatakan.</p>
<p>Bloom revisi dipilih dari proses minimum: mengingat, memahami, menerapkan, menganalisis, mengevaluasi, atau mencipta. Kata kerja, bentuk PG, dan tingkat Barrett tidak menentukan Bloom secara otomatis. Inferensi dapat berada di C2; memilih hasil karya yang tersedia tidak otomatis C6. Jika proses jelas berbeda dari target, kriteria 1 dan 2 Barrett/Bloom maksimal 1.</p>
<p>CEFR adalah perkiraan tuntutan kosakata, sintaksis, wacana dan tugas berdasarkan deskriptor membaca, bukan sertifikasi. Panjang teks dan kelas siswa hanya konteks. Grammar membedakan kesalahan nyata, variasi bahasa yang sah, dan distraktor yang sengaja salah sebagai konstruk soal.</p>
<h2>5. Kunci dan PG kompleks kategori</h2><p>Satu stem dengan beberapa baris pernyataan dan kolom True/False, Yes/No atau kategori lain merupakan satu butir. Satu kategori dipilih untuk setiap baris. Kunci ditampilkan per baris dengan alasan dan kutipan stimulus. Tidak ada kewajiban proporsi True/False tertentu. Pernyataan yang tidak disebutkan tidak otomatis False; ikuti instruksi dan bukti. Baris yang tidak dapat diputuskan ditandai Informasi tidak cukup, bukan ditebak. Seluruh baris harus diperiksa, termasuk pada soal revisi.</p>
<h2>6. Contoh keputusan dan kalibrasi</h2><ul><li>Target Literal, jawaban dinyatakan jelas dan opsi tidak ambigu: kategori rendah dalam taksonomi tetap dapat mendapat nilai penuh.</li><li>Target C4 tetapi jawaban cukup dengan mengambil detail eksplisit: jelaskan proses yang sebenarnya; kriteria 1 dan 2 Bloom maksimal 1.</li><li>Dua jawaban sama kuat pada PG satu jawaban: kunci Ambigu; label keseluruhan maksimal Kurang Sesuai, meskipun bahasa baik.</li><li>Satu baris True/False tidak memiliki bukti: status baris Informasi tidak cukup, tanpa memaksakan False.</li><li>Semua level 4 tetapi ditemukan isu material: label tidak boleh Sangat Sesuai.</li><li>Input identik dengan level kriteria identik selalu menghasilkan skor/label identik. Penafsiran level dan klasifikasi masih dapat bervariasi.</li></ul>
<p>Untuk mengukur akurasi, siapkan soal acuan yang kuncinya, kategori dan alasan telah disepakati guru. Jalankan tiap soal beberapa kali dengan konfigurasi tetap; bandingkan kunci per respons, kesepakatan Barrett/Bloom, selisih skor tiap kategori, dan kestabilan label. Perbedaan perlu ditelaah, bukan ditutupi dengan menyimpan hasil pertama. Paket ini belum diuji terhadap kumpulan soal acuan guru.</p>
<h2>7. Batas pemeriksaan otomatis</h2><p>Kode memeriksa kelengkapan 28 nilai kriteria, batas nilai, keberadaan kutipan dalam input, perhitungan, label, status kunci dan kelengkapan revisi. Keberadaan kutipan tidak membuktikan bahwa penafsirannya benar. Pemeriksaan isi dilakukan dalam permintaan yang sama, bukan penilaian independen kedua. Pergantian layanan cadangan tetap memakai rubrik yang sama tetapi dapat mengubah interpretasi.</p>
<h2>Landasan dan bacaan</h2><ul>${REFERENCES.map(r=>'<li><a href="'+e(r.url)+'" target="_blank" rel="noopener noreferrer">'+e(r.title)+'</a></li>').join('')}<li><a href="https://www.coe.int/en/web/common-european-framework-reference-languages/cefr-descriptors">Council of Europe — CEFR descriptors</a></li></ul><p>Landasan digunakan untuk definisi konstruk. Formula, bobot, level 0–4, serta pembatas label merupakan rancangan operasional aplikasi.</p></main></html>`;
await writeFile(new URL('../public/rubrik.html',import.meta.url),html);
